services:
  ganache:
    image: hybuild/ganache
    restart: on-failure
    ports:
      - 7545:7545
    volumes:
      - ganache-db:/db
 
  swagger:
    image: hybuild/swagger
    restart: always
    ports:
      - 7777:7777
      - 8080:8080
 
volumes:
  ganache-db:
