services:
  ganache:
    image: hybuild/ganache:poe7
    restart: on-failure
    ports:
      - 7545:7545
    volumes:
      - ganache-db:/db
 
  swagger:
    image: hybuild/swagger:poe7
    restart: always
    ports:
      - 8080:8080
 
volumes:
  ganache-db: